// ============================================
// game-data.ts — Centralized Game Metadata
// Single source of truth for all game info.
// Update here → all pages sync automatically.
// ============================================

export interface GameMeta {
  name: string;
  slug: string;
  headerImage: string;
  description: string;
  releaseYear: string;
  developer: string;
  publisher: string;
  tags: string[];
  emoji?: string; // for Popular Games etc.
}

export const ALL_GAMES: Record<string, GameMeta> = {
  'elden-ring': {
    name: 'Elden Ring',
    slug: 'elden-ring',
    headerImage: '/images/games/elden-ring-header-v20260806.jpg',
    description: "FromSoftware's masterpiece — an open-world action RPG set in the Lands Between. Explore a vast dark fantasy world, face demigods, and become the Elden Lord.",
    releaseYear: '2022',
    developer: 'FromSoftware',
    publisher: 'Bandai Namco',
    tags: ['Action RPG', 'Open World', 'Soulslike', 'Dark Fantasy'],
    emoji: '⚔️',
  },
  'baldurs-gate-3': {
    name: "Baldur's Gate 3",
    slug: 'baldurs-gate-3',
    headerImage: '/images/games/baldurs-gate-3-header-v20260806.jpg',
    description: "Larian Studios' award-winning CRPG set in the Dungeons & Dragons universe. Experience deep storytelling, tactical turn-based combat, and unprecedented player freedom.",
    releaseYear: '2023',
    developer: 'Larian Studios',
    publisher: 'Larian Studios',
    tags: ['CRPG', 'Turn-Based', 'D&D', 'Fantasy', 'Story-Rich'],
    emoji: '🎲',
  },
  'star-wars-zero-company': {
    name: 'Star Wars Zero Company',
    slug: 'star-wars-zero-company',
    headerImage: '/images/games/star-wars-zero-company-header-v20260825.jpg',
    description: "Bit Reactor and Respawn's single-player turn-based tactics game set during the final days of the Clone Wars. Command Hawks and an elite squad of mercenaries in covert operations against the Separatist-aligned Infinite Coil cult. The most ambitious Star Wars strategy game in years, from the former Firaxis team behind XCOM.",
    releaseYear: '2026',
    developer: 'Bit Reactor / Respawn Entertainment',
    publisher: 'Electronic Arts',
    tags: ['Turn-Based Tactics', 'Star Wars', 'Clone Wars', 'Strategy', 'Single-Player', 'XCOM-Style'],
    emoji: '⭐',
  },
  'witcher-3': {
    name: 'The Witcher 3: Wild Hunt',
    slug: 'witcher-3',
    headerImage: '/images/games/witcher-3-header-v20260829.jpg',
    description: "CD Projekt Red's landmark open-world RPG. Geralt of Rivia hunts monsters across Velen, Novigrad, and Skellige in one of the most acclaimed games ever made. The Remastered edition arrives September 29, 2026 as a free upgrade, with the third expansion Songs of the Past coming in 2027.",
    releaseYear: '2015',
    developer: 'CD Projekt Red',
    publisher: 'CD Projekt',
    tags: ['Open World', 'Action RPG', 'Dark Fantasy', 'Story-Rich', 'Single-Player'],
    emoji: '🐺',
  },
  'resonance-plague-tale-legacy': {
    name: 'Resonance: A Plague Tale Legacy',
    slug: 'resonance-plague-tale-legacy',
    headerImage: '/images/games/resonance-plague-tale-legacy-header-v20260825.jpg',
    description: "Asobo Studio's prequel to A Plague Tale, set 15 years before Requiem. Play as Sophia, a treasure hunter on Crete's Minotaur Island, wielding dual swords in a Ghost of Tsushima-inspired combat system. Day one on Xbox Game Pass and PC Game Pass.",
    releaseYear: '2026',
    developer: 'Asobo Studio',
    publisher: 'Focus Entertainment',
    tags: ['Action-Adventure', 'Prequel', 'Medieval', 'Mythology', 'Single-Player', 'Stealth'],
    emoji: '🏛️',
  },
  'rampage-evolution': {
    name: 'Rampage Evolution',
    slug: 'rampage-evolution',
    headerImage: '/images/games/rampage-evolution-header-v20260806.jpg',
    description: "Tencent's massive 2026 summer hit — open-world survival PVP with mutation-based evolution, territory control, and base building. 40 million pre-registrations worldwide.",
    releaseYear: '2026',
    developer: 'Tencent',
    publisher: 'Tencent',
    tags: ['Survival', 'Open World', 'Evolution', 'PVP', 'Multiplayer'],
    emoji: '🦖',
  },
  'sir-we-have-an-orc-problem': {
    name: 'Sir, We Have an Orc Problem',
    slug: 'sir-we-have-an-orc-problem',
    headerImage: '/images/games/sir-we-have-an-orc-problem-header-v20260806.jpg',
    description: 'A progressive tower defense roguelite from Mumpitz Games. Defend against 100,000+ physics-driven orcs with turrets, lasers, and nukes in a satisfying fail-forward loop.',
    releaseYear: '2026',
    developer: 'Mumpitz Games',
    publisher: 'Mumpitz Games',
    tags: ['Tower Defense', 'Roguelite', 'Indie', 'Strategy', 'Incremental'],
    emoji: '🧌',
  },
  'beast-of-reincarnation': {
    name: 'Beast of Reincarnation',
    slug: 'beast-of-reincarnation',
    headerImage: '/images/games/beast-of-reincarnation-header-v20260806.jpg',
    description: "Game Freak's dark action RPG set in post-apocalyptic Japan. Fight alongside your dog Koo in a hybrid real-time and tactical combat system. Day one on Game Pass.",
    releaseYear: '2026',
    developer: 'Game Freak',
    publisher: 'Fictions',
    tags: ['Action RPG', 'Post-Apocalyptic', 'Single-Player', 'Soulslike', 'Story-Rich'],
    emoji: '🐺',
  },
  'mistfall-hunter': {
    name: 'Mistfall Hunter',
    slug: 'mistfall-hunter',
    headerImage: '/images/games/mistfall-hunter-header-v20260806.jpg',
    description: 'Bellring Games\' dark fantasy PvPvE extraction RPG. Six classes, lethal death penalty, crossplay on PC, PS5, and Xbox. Day one on Game Pass.',
    releaseYear: '2026',
    developer: 'Bellring Games',
    publisher: 'Skystone Games',
    tags: ['Extraction RPG', 'PvPvE', 'Dark Fantasy', 'Multiplayer', 'Soulslike'],
    emoji: '🌫️',
  },
  'league-of-legends': {
    name: 'League of Legends',
    slug: 'league-of-legends',
    headerImage: '/images/games/league-of-legends-header-v20260806.jpg',
    description: "Riot Games' genre-defining MOBA. Five-on-five team fights, ever-evolving champions, and a ranked ladder that has defined competitive PC gaming for over 15 years.",
    releaseYear: '2009',
    developer: 'Riot Games',
    publisher: 'Riot Games',
    tags: ['MOBA', 'Competitive', 'Multiplayer', 'Strategy', 'Esports'],
    emoji: '🏆',
  },
  'black-myth-zhong-kui': {
    name: 'Black Myth: Zhong Kui',
    slug: 'black-myth-zhong-kui',
    headerImage: '/images/games/black-myth-zhong-kui-header-v20260806.jpg',
    description: "Game Science's next Black Myth title — a dark Chinese mythology ARPG featuring Zhong Kui, the legendary ghost-hunting deity. Announced at Gamescom 2025. Coming to PC, PS5, and Xbox Series X/S.",
    releaseYear: 'TBA',
    developer: 'Game Science',
    publisher: 'Game Science',
    tags: ['Action RPG', 'Chinese Mythology', 'Dark Fantasy', 'Soulslike', 'Single-Player'],
    emoji: '👹',
  },
  'black-myth-wukong': {
    name: 'Black Myth: Wukong',
    slug: 'black-myth-wukong',
    headerImage: '/images/games/black-myth-wukong-header-v20260806.jpg',
    description: "Game Science's landmark Chinese mythology action RPG. Play as the Destined One in a breathtaking journey inspired by Journey to the West. 2024 TGA Best Action Game winner, 25+ million copies sold, the game that put Chinese AAA on the global map.",
    releaseYear: '2024',
    developer: 'Game Science',
    publisher: 'Game Science',
    tags: ['Action RPG', 'Chinese Mythology', 'Soulslike', 'Single-Player', 'Boss Rush'],
    emoji: '🐒',
  },
  'monster-hunter-wilds': {
    name: 'Monster Hunter Wilds',
    slug: 'monster-hunter-wilds',
    headerImage: '/images/games/monster-hunter-wilds-header-v20260806.jpg',
    description: "Capcom's flagship hunting action RPG — explore dynamic ecosystems, hunt massive monsters solo or in co-op, and craft powerful gear. The next evolution of the Monster Hunter series, with cross-platform play on PC, PS5, and Xbox.",
    releaseYear: '2025',
    developer: 'Capcom',
    publisher: 'Capcom',
    tags: ['Action RPG', 'Co-op', 'Hunting', 'Open World', 'Multiplayer'],
    emoji: '🐉',
  },
  'silent-hill-f': {
    name: 'Silent Hill f',
    slug: 'silent-hill-f',
    headerImage: '/images/games/silent-hill-f-header-v20260806.jpg',
    description: "Konami's haunting return to Silent Hill — a psychological horror masterpiece set in 1960s Japan. Play as Hinako Shimizu in the fog-shrouded town of Ebisugaoka. Five endings, deep NG+ system, and one of 2025's most acclaimed horror games.",
    releaseYear: '2025',
    developer: 'Konami',
    publisher: 'Konami',
    tags: ['Survival Horror', 'Psychological Horror', 'Single-Player', 'Story-Rich', 'Japanese Horror'],
    emoji: '🌸',
  },
  'palworld': {
    name: 'Palworld',
    slug: 'palworld',
    headerImage: '/images/games/palworld-header-v20260806.jpg',
    description: "Pocketpair's survival crafting phenomenon — catch, breed, and battle 287 Pals across floating islands and the World Tree. 40 million players. 1.0 full release July 2026.",
    releaseYear: '2026',
    developer: 'Pocketpair',
    publisher: 'Pocketpair',
    tags: ['Survival', 'Crafting', 'Creature Collection', 'Open World', 'Multiplayer'],
    emoji: '🐾',
  },
  'project-zomboid': {
    name: 'Project Zomboid',
    slug: 'project-zomboid',
    headerImage: '/images/games/project-zomboid-header-v20260806.jpg',
    description: "The Indie Stone's hardcore open-world zombie survival sandbox. Loot, craft, build, farm, and fight to survive in a relentless post-apocalyptic Kentucky. 13 years in Early Access, Build 42 stable release July 2026.",
    releaseYear: '2013',
    developer: 'The Indie Stone',
    publisher: 'The Indie Stone',
    tags: ['Survival', 'Zombies', 'Open World', 'Sandbox', 'Multiplayer'],
    emoji: '🧟',
  },
  'fortnite': {
    name: 'Fortnite',
    slug: 'fortnite',
    headerImage: '/images/games/fortnite-header-v20260806.jpg',
    description: "Epic Games' genre-defining battle royale. Drop onto an ever-evolving island, build, battle, and adapt through seasonal events, massive crossovers, and zero-build modes that keep the meta fresh.",
    releaseYear: '2017',
    developer: 'Epic Games',
    publisher: 'Epic Games',
    tags: ['Battle Royale', 'Shooter', 'Multiplayer', 'Building', 'Cross-Platform'],
    emoji: '🏝️',
  },
  'marvel-tokon': {
    name: 'Marvel Tōkon: Fighting Souls',
    slug: 'marvel-tokon',
    headerImage: '/images/games/marvel-tokon-header-v20260807.jpg',
    description: "Arc System Works' 4v4 Marvel tag fighter featuring 20 launch characters across five teams. Shared health bar, progressive character unlocks, and the deepest assist system in the genre. Day one on PC, PS5, and PS4.",
    releaseYear: '2026',
    developer: 'Arc System Works',
    publisher: 'PlayStation Publishing / Marvel Games',
    tags: ['Fighting', 'Tag Fighter', '4v4', 'Superhero', 'Competitive'],
    emoji: '💥',
  },
  'apex-legends': {
    name: 'Apex Legends',
    slug: 'apex-legends',
    headerImage: '/images/games/apex-legends-header-v20260807b.jpg',
    description: "Respawn's genre-leading hero battle royale — 28 Legends, seasonal meta shifts, and the best gunplay in the genre. Season 30 Marked brings Bloodhound's Allfather's Cloak and the biggest systemic overhaul in years.",
    releaseYear: '2019',
    developer: 'Respawn Entertainment',
    publisher: 'Electronic Arts',
    tags: ['Battle Royale', 'Shooter', 'Hero Shooter', 'Multiplayer', 'Competitive'],
    emoji: '🎯',
  },
  'big-walk': {
    name: 'Big Walk',
    slug: 'big-walk',
    headerImage: '/images/games/big-walk-header-v20260806.jpg',
    description: "House House's 92-rated co-op adventure where communication is the real mechanic. Explore a vast Australian island with up to 12 friends, solve proximity-voice puzzles, and discover why walking and talking together is 2026's most talked-about gaming experience.",
    releaseYear: '2026',
    developer: 'House House',
    publisher: 'Panic',
    tags: ['Co-op', 'Puzzle', 'Adventure', 'Exploration', 'Cross-Platform'],
    emoji: '🚶',
  },
  'phantom-blade-zero': {
    name: 'Phantom Blade Zero',
    slug: 'phantom-blade-zero',
    headerImage: '/images/games/phantom-blade-zero-header-v20260807b.jpg',
    description: "S-GAME's Kungfupunk action RPG — play as Soul, an elite assassin with 66 days to live, in a dark wuxia world blending martial arts and steampunk. 30+ weapons, 8 endings, combat inspired by Hong Kong action cinema. Launching October 29, 2026 on PS5 and PC.",
    releaseYear: '2026',
    developer: 'S-GAME',
    publisher: 'S-GAME',
    tags: ['Action RPG', 'Wuxia', 'Kungfupunk', 'Martial Arts', 'Single-Player'],
    emoji: '🗡️',
  },
  'marvel-snap': {
    name: 'Marvel Snap',
    slug: 'marvel-snap',
    headerImage: '/images/games/marvel-snap-header-v20260809.jpg',
    description: "Second Dinner's strategic Marvel collectible card game — six-turn Three Locations battles featuring hundreds of heroes and villains. Free-to-play on iOS, Android, and Steam with cross-progression. The August 9 patch refunds Nexus Event tickets and rebalances nine cards including Hellcow and Jane Foster.",
    releaseYear: '2022',
    developer: 'Second Dinner',
    publisher: 'Skystone Games',
    tags: ['CCG', 'Card Game', 'Marvel', 'Free-to-Play', 'Cross-Platform'],
    emoji: '🃏',
  },
  'grain-rot': {
    name: 'GRAIN ROT',
    slug: 'grain-rot',
    headerImage: '/images/games/grain-rot-header-v20260810.jpg',
    description: "Beck & Branch Games' viral co-op extraction horror — control fragile wooden vessels inhabited by Living Sparks, descend into shifting burned ruins, steal furniture, and rebuild your Sanctuary Outpost. 350,000+ demo downloads and a Top 15 Steam Next Fest demo.",
    releaseYear: '2026',
    developer: 'Beck & Branch Games',
    publisher: 'Neem Interactive',
    tags: ['Co-op', 'Extraction Horror', 'Roguelike', 'Base Building', 'Indie'],
    emoji: '🔥',
  },
  'mortal-shell-2': {
    name: 'Mortal Shell II',
    slug: 'mortal-shell-2',
    headerImage: '/images/games/mortal-shell-2-header-v20260810.jpg',
    description: "Cold Symmetry's standalone sequel to the 2020 dark fantasy soulslike. Stamina bar removed, 8 playable Shells, 60+ dungeons in a compact open world. Launching August 20, 2026 on PC, PS5, and Xbox Series X/S.",
    releaseYear: '2026',
    developer: 'Cold Symmetry',
    publisher: 'Playstack',
    tags: ['Action RPG', 'Soulslike', 'Dark Fantasy', 'Single-Player', 'Open World'],
    emoji: '💀',
  },
  'world-of-warcraft': {
    name: 'World of Warcraft',
    slug: 'world-of-warcraft',
    headerImage: '/images/games/world-of-warcraft-header-v20260811.jpg',
    description: "Blizzard Entertainment's legendary MMORPG. The Midnight expansion continues with Patch 12.1: Curse of Ula'tek — explore the Coiled Isle, conquer the Venomous Abyss raid, and master the overhauled class meta.",
    releaseYear: '2004',
    developer: 'Blizzard Entertainment',
    publisher: 'Blizzard Entertainment',
    tags: ['MMORPG', 'Fantasy', 'Multiplayer', 'Open World', 'PvE', 'PvP'],
    emoji: '🐉',
  },
  'dota-2': {
    name: 'Dota 2',
    slug: 'dota-2',
    headerImage: '/images/games/dota-2-header-v20260811.jpg',
    description: "Valve's flagship MOBA — 124 heroes, 5v5 strategy, and the most prestigious annual esports championship on the planet. The International 2026 returns to Shanghai August 13-23 with a $1.6M base prize pool, but a pre-tournament match-fixing scandal has already rewritten the storyline.",
    releaseYear: '2013',
    developer: 'Valve',
    publisher: 'Valve',
    tags: ['MOBA', 'Esports', 'Strategy', 'Competitive', '5v5'],
    emoji: '⚔️',
  },
  'ghost-recon-wildlands': {
    name: "Ghost Recon Wildlands",
    slug: 'ghost-recon-wildlands',
    headerImage: '/images/games/ghost-recon-wildlands-header-v20260811.jpg',
    description: "Ubisoft's definitive open-world tactical shooter — lead an elite Ghost team across a vast, living Bolivia to dismantle the Santa Blanca cartel. The free August 2026 Last Rites update adds a new story mission, 4K/60 FPS console upgrade, and the return of the Predator event, driving a 418% player surge on Steam.",
    releaseYear: '2017',
    developer: 'Ubisoft Paris',
    publisher: 'Ubisoft',
    tags: ['Tactical Shooter', 'Open World', 'Co-op', 'Stealth', 'Military'],
    emoji: '🎖️',
  },
  'marvel-rivals': {
    name: 'Marvel Rivals',
    slug: 'marvel-rivals',
    headerImage: '/images/games/marvel-rivals-header-v20260813.jpg',
    description: "NetEase Games' 6v6 hero shooter featuring 53+ Marvel heroes and villains. Team-Up abilities, destructible environments, and seasonal events. Season 9.5 brings The Hood and the Summer Finale '26 festival at Hellfire Bay Beach — running through September 24.",
    releaseYear: '2024',
    developer: 'NetEase Games',
    publisher: 'NetEase Games / Marvel Games',
    tags: ['Hero Shooter', '6v6', 'Marvel', 'Multiplayer', 'Competitive'],
    emoji: '🦸',
  },
  'marvels-wolverine': {
    name: "Marvel's Wolverine",
    slug: 'marvels-wolverine',
    headerImage: '/images/games/marvels-wolverine-header-v20260814.jpg',
    description: "Insomniac Games' brutal single-player action-adventure. Control Logan as he tears through the Reavers with adamantium claws, a three-tier Rage system, and cinematic combat. PS5 exclusive, launching September 15, 2026.",
    releaseYear: '2026',
    developer: 'Insomniac Games',
    publisher: 'Sony Interactive Entertainment / Marvel Games',
    tags: ['Action-Adventure', 'Marvel', 'Superhero', 'Single-Player', 'PS5 Exclusive'],
    emoji: '💢',
  },
  'peak': {
    name: 'PEAK',
    slug: 'peak',
    headerImage: '/images/games/peak-header-v20260815.jpg',
    description: "Aggro Crab and Landfall's four-player co-op climbing game. Scramble up a procedurally generated mountain with friends, manage stamina and scouts, and survive bizarre hazards. The Final Ascent update adds the Gloom and Citadel biomes, Ascent 8, and a secret ending — and the game is 50% off ($3.99) through August 18, 2026.",
    releaseYear: '2025',
    developer: 'Aggro Crab / Landfall Games',
    publisher: 'Aggro Crab / Evil Landfall',
    tags: ['Co-op', 'Climbing', 'Indie', 'Multiplayer', 'Roguelite'],
    emoji: '⛰️',
  },
  'the-sinking-city-2': {
    name: 'The Sinking City 2',
    slug: 'the-sinking-city-2',
    headerImage: '/images/games/the-sinking-city-2-header-v20260816.jpg',
    description: "Frogwares' Lovecraftian survival horror set in flooded 1920s Arkham. Manage scarce ammo, investigate occult crimes, and defy an eldritch deity as Calvin Rafferty. Launching August 18, 2026 on PC, PS5, and Xbox Series X|S — Premium Edition unlocks 24 hours early.",
    releaseYear: '2026',
    developer: 'Frogwares',
    publisher: 'Frogwares',
    tags: ['Survival Horror', 'Lovecraftian', 'Action-Adventure', 'Single-Player', 'Investigation'],
    emoji: '🌊',
  },
  'helldivers-2': {
    name: 'Helldivers 2',
    slug: 'helldivers-2',
    headerImage: '/images/games/helldivers-2-header-v20260826.jpg',
    description: "Arrowhead Game Studios' co-op tactical shooter. Drop into a satirical sci-fi galaxy and fight for Super Earth against bugs, bots, and the Illuminate. The Devoid of Liberty update opens the Void biome, adds the Wretch and Crusher enemies, raises the level cap to 300, and brings SEAF support squads.",
    releaseYear: '2024',
    developer: 'Arrowhead Game Studios',
    publisher: 'Sony Interactive Entertainment',
    tags: ['Co-op Shooter', 'Tactical', 'Sci-Fi', 'Multiplayer', 'Third-Person'],
    emoji: '🪖',
  },
  'metal-gear-solid-master-collection-vol-2': {
    name: 'Metal Gear Solid: Master Collection Vol. 2',
    slug: 'metal-gear-solid-master-collection-vol-2',
    headerImage: '/images/games/metal-gear-solid-master-collection-vol-2-header-v20260826.jpg',
    description: "Konami's definitive Metal Gear Solid collection. MGS4: Guns of the Patriots escapes its 18-year PS3 prison alongside Peace Walker HD and Ghost Babel. Launching August 27, 2026 on PS5, Xbox Series X|S, Switch 2, Switch, and PC.",
    releaseYear: '2026',
    developer: 'Konami Digital Entertainment',
    publisher: 'Konami',
    tags: ['Stealth', 'Action', 'Classic', 'Single-Player', 'Collection'],
    emoji: '📦',
  },
  'blood-of-dawnwalker': {
    name: 'The Blood of Dawnwalker',
    slug: 'blood-of-dawnwalker',
    headerImage: '/images/games/blood-of-dawnwalker-header-v20260827.jpg',
    description: "Rebel Wolves' dark fantasy open-world RPG from The Witcher 3's director. Play as Coen — human by day, vampire by night — with 30 in-game days to save his family from vampire lord Brencis in 14th-century Vale Sangora. Time is a currency: every quest spends it. Launching September 3, 2026 on PC, PS5, and Xbox Series X|S.",
    releaseYear: '2026',
    developer: 'Rebel Wolves',
    publisher: 'Bandai Namco Entertainment',
    tags: ['Action RPG', 'Open World', 'Dark Fantasy', 'Vampires', 'Single-Player', 'Story-Rich'],
    emoji: '🧛',
  },
  'nioh-3': {
    name: 'Nioh 3',
    slug: 'nioh-3',
    headerImage: '/images/games/nioh-3-header-v20260818.jpg',
    description: "Team NINJA's dark samurai action RPG — play as Takechiyo across time-hopping chapters of feudal Japan, from the 1622 Edo period to Keian-era 1651. The first DLC, Hell Rising, arrives August 19, 2026 with the new Hoko & Shield weapon, the Hundred Demon Realms Picture Scroll, and the Enlightened One's Journey difficulty on PS5 and PC.",
    releaseYear: '2026',
    developer: 'Team NINJA',
    publisher: 'Koei Tecmo',
    tags: ['Action RPG', 'Soulslike', 'Dark Fantasy', 'Samurai', 'Single-Player'],
    emoji: '⛩️',
  },
  'onimusha-way-of-the-sword': {
    name: 'Onimusha: Way of the Sword',
    slug: 'onimusha-way-of-the-sword',
    headerImage: '/images/games/onimusha-way-of-the-sword-header-v20260901.jpg',
    description: "Capcom's revival of the legendary samurai action series after 20 years, powered by RE Engine. Play as Miyamoto Musashi in demon-infested Sengoku-era Japan, mastering the Issen counter system and wielding the Oni Gauntlet. IGN 10/10, Metacritic 86, Gamescom Best Gameplay. Launching September 4, 2026 on PS5, Xbox Series X|S, Nintendo Switch 2, and PC.",
    releaseYear: '2026',
    developer: 'Capcom',
    publisher: 'Capcom',
    tags: ['Action-Adventure', 'Samurai', 'Dark Fantasy', 'Capcom', 'Single-Player', 'RE Engine'],
    emoji: '🏯',
  },
  'dragons-dogma-2': {
    name: "Dragon's Dogma 2",
    slug: 'dragons-dogma-2',
    headerImage: '/images/games/dragons-dogma-2-header-v20260902.jpg',
    description: "Capcom's acclaimed open-world action RPG where you hunt the Dragon as the Arisen, commanding a party of Pawns. Title Update 3.2 (September 2026) rebuilds the save system, adds Dragonsbaulk Draught to cure Dragonsplague, six weapon-skill slots, a full Pawn AI overhaul, and 60 FPS performance modes. The Dark Arisen expansion arrives October 9, 2026 with the frozen Norgan region and Relic Expedition Cycle.",
    releaseYear: '2024',
    developer: 'Capcom',
    publisher: 'Capcom',
    tags: ['Action RPG', 'Open World', 'Dark Fantasy', 'Capcom', 'Single-Player', 'Pawns'],
    emoji: '🐲',
  },
};

/** Ordered list for homepage "Popular Games" section */
export const POPULAR_GAMES_ORDER: string[] = [
  'dragons-dogma-2',
  'witcher-3',
  'blood-of-dawnwalker',
  'onimusha-way-of-the-sword',
  'helldivers-2',
  'metal-gear-solid-master-collection-vol-2',
  'resonance-plague-tale-legacy',
  'star-wars-zero-company',
  'nioh-3',
  'the-sinking-city-2',
  'peak',
  'marvels-wolverine',
  'ghost-recon-wildlands',
  'dota-2',
  'world-of-warcraft',
  'mortal-shell-2',
  'grain-rot',
  'marvel-snap',
  'phantom-blade-zero',
  'marvel-tokon',
  'apex-legends',
  'big-walk',
  'black-myth-wukong',
  'elden-ring',
  'baldurs-gate-3',
  'project-zomboid',
  'rampage-evolution',
  'sir-we-have-an-orc-problem',
  'beast-of-reincarnation',
  'mistfall-hunter',
  'league-of-legends',
  'black-myth-zhong-kui',
  'monster-hunter-wilds',
  'silent-hill-f',
  'palworld',
  'fortnite',
  'marvel-rivals',
];

/** Lightweight view for pages that only need name + image */
export interface GameCard {
  slug: string;
  name: string;
  image: string;
  emoji?: string;
}

export function getGameCard(slug: string): GameCard | undefined {
  const g = ALL_GAMES[slug];
  if (!g) return undefined;
  return { slug: g.slug, name: g.name, image: g.headerImage, emoji: g.emoji };
}

export function getPopularGames(): GameCard[] {
  return POPULAR_GAMES_ORDER.map((slug) => getGameCard(slug)!).filter(Boolean);
}
